const TSHIRT_NORMALIZATION_MAP: Record<string, string> = {
  'youth extra small': 'Youth Extra Small',
  'youth xs': 'Youth Extra Small',
  'youth x-small': 'Youth Extra Small',
  yxs: 'Youth Extra Small',
  'youth small': 'Youth Small',
  'youth s': 'Youth Small',
  'youth s.': 'Youth Small',
  ys: 'Youth Small',
  'youth medium': 'Youth Medium',
  'youth m': 'Youth Medium',
  'youth m.': 'Youth Medium',
  ym: 'Youth Medium',
  'youth large': 'Youth Large',
  'youth l': 'Youth Large',
  'youth l.': 'Youth Large',
  yl: 'Youth Large',
  'youth extra large': 'Youth Extra Large',
  'youth xl': 'Youth Extra Large',
  'youth x-large': 'Youth Extra Large',
  yxl: 'Youth Extra Large',

  // Child sizes (normalized to Youth equivalents)
  'child extra small': 'Youth Extra Small',
  'child xs': 'Youth Extra Small',
  'child small': 'Youth Small',
  'child s': 'Youth Small',
  'child medium': 'Youth Medium',
  'child m': 'Youth Medium',
  'child large': 'Youth Large',
  'child l': 'Youth Large',
  'child xl': 'Youth Extra Large',
  "child's large": 'Youth Large',
  'childs large': 'Youth Large',
  "child's xl": 'Youth Extra Large',
  'childs xl': 'Youth Extra Large',

  // Adult sizes - standard
  'extra small': 'Extra Small',
  'x-small': 'Extra Small',
  xs: 'Extra Small',
  xsmall: 'Extra Small',
  small: 'Small',
  s: 'Small',
  's.': 'Small',
  medium: 'Medium',
  med: 'Medium',
  m: 'Medium',
  'm.': 'Medium',
  large: 'Large',
  l: 'Large',
  'l.': 'Large',
  'extra large': 'Extra Large',
  'x-large': 'Extra Large',
  xl: 'Extra Large',
  xlarge: 'Extra Large',
  '2x': '2XL',
  '2xl': '2XL',
  '2 xl': '2XL',
  xxl: '2XL',
  '3x': '3XL',
  '3xl': '3XL',
  '3 xl': '3XL',
  '4x': '4XL',
  '4xl': '4XL',
  '4 xl': '4XL',

  // Adult sizes with "Adult" prefix
  'adult small': 'Adult Small',
  'adult s': 'Adult Small',
  'adult medium': 'Adult Medium',
  'adult m': 'Adult Medium',
  'adult large': 'Adult Large',
  'adult l': 'Adult Large',
  'adult xl': 'Adult Extra Large',
  'm womens': 'Adult Medium Womens',
  'size 12': 'Adult Medium',
  'aduit medium': 'Adult Medium',
};

export function normalizeTshirtSize(value: string): string {
  if (!value.trim()) return '';
  const normalized = value.trim().toLowerCase();
  return TSHIRT_NORMALIZATION_MAP[normalized] ?? value.trim();
}
